USE BookEcommerceDB
GO

-- CLIENTE
CREATE TABLE TIPO_TELEFONE (
   ID INT IDENTITY(1,1)		  NOT NULL,
   DESCRICAO VARCHAR (20)     NOT NULL,
   DATA_CADASTRO DATE		  NOT NULL
   PRIMARY KEY (ID)
);

CREATE TABLE TELEFONE (
   ID INT IDENTITY(1,1)		  NOT NULL,
   DDD VARCHAR (2)			  NOT NULL,
   NUMERO VARCHAR (10)		  NOT NULL,
   ID_TIPO_TELEFONE INT		  NOT NULL,
   DATA_CADASTRO DATE		  NOT NULL
   PRIMARY KEY (ID),
   FOREIGN KEY (ID_TIPO_TELEFONE) REFERENCES TIPO_TELEFONE(ID)
);

CREATE TABLE STATUS_CLIENTE (
   ID INT IDENTITY(1,1)		  NOT NULL,
   DESCRICAO VARCHAR (20)     NOT NULL,
   DATA_CADASTRO DATE		  NOT NULL
   PRIMARY KEY (ID)
);

-- CLIENTE