USE BookEcommerceDB
GO

-- GERAL

CREATE TABLE PERFIL (
   ID INT IDENTITY(1,1) NOT NULL,
   DESCRICAO VARCHAR (100) NOT NULL,
   DATA_CADASTRO DATE NOT NULL
   PRIMARY KEY (ID)
);

CREATE TABLE USUARIO (
   ID INT IDENTITY(1,1) NOT NULL,
   LOGIN_USUARIO VARCHAR (50) NOT NULL,
   SENHA VARCHAR (20) NOT NULL,
   ID_PERFIL INT NOT NULL,
   DATA_CADASTRO DATE NOT NULL
   PRIMARY KEY (ID),
   FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID)
);

CREATE TABLE OPERACAO (
   ID INT IDENTITY(1,1) NOT NULL,
   DESCRICAO VARCHAR (100) NOT NULL,
   DATA_CADASTRO DATE NOT NULL
   PRIMARY KEY (ID)
);

CREATE TABLE CONTROLE_LOG (
   ID INT IDENTITY(1,1) NOT NULL,
   DATA_HORA_OCORRIDO DATE NOT NULL,
   ID_OPERACAO INT NOT NULL,
   DATA_CADASTRO DATE NOT NULL
   PRIMARY KEY (ID),
   FOREIGN KEY (ID_OPERACAO) REFERENCES OPERACAO(ID)
);

-- GERAL

-- CLIENTE
CREATE TABLE TIPO_TELEFONE (
   ID INT IDENTITY(1,1) NOT NULL,
   DESCRICAO VARCHAR (20) NOT NULL,
   DATA_CADASTRO DATE NOT NULL
   PRIMARY KEY (ID)
);

CREATE TABLE TELEFONE (
   ID INT IDENTITY(1,1) NOT NULL,
   DDD VARCHAR (2) NOT NULL,
   NUMERO VARCHAR (10) NOT NULL,
   ID_TIPO_TELEFONE INT NOT NULL,
   DATA_CADASTRO DATE NOT NULL
   PRIMARY KEY (ID),
   FOREIGN KEY (ID_TIPO_TELEFONE) REFERENCES TIPO_TELEFONE(ID)
);

CREATE TABLE STATUS_CLIENTE (
   ID INT IDENTITY(1,1) NOT NULL,
   DESCRICAO VARCHAR (20) NOT NULL,
   DATA_CADASTRO DATE NOT NULL
   PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIA_TRANSACAO
   ID INT IDENTITY(1,1)	NOT NULL,
   DESCRICAO VARCHAR (20) NOT NULL,
   DATA_CADASTRO DATE NOT NULL
   PRIMARY KEY (ID)
);

CREATE TABLE TRANSACAO (
   ID INT IDENTITY(1,1) NOT NULL,
   DESCRICAO_TRANSACAO VARCHAR(100) NOT NULL,
   ID_CATEGORIA_TRANSACAO INT NOT NULL,
   ID_CONTROLE_LOG INT NOT NULL,
   DATA_CADASTRO DATE NOT NULL
   PRIMARY KEY (ID),
   FOREIGN KEY (ID_CATEGORIA_TRANSACAO) REFERENCES CATEGORIA_TRANSACAO(ID),
   FOREIGN KEY (ID_CONTROLE_LOG) REFERENCES CONTROLE_LOG(ID)
);

-- CLIENTE